language: objective-c
osx_image: xcode61
rvm:
- 2.1.2

before_install:
- chmod a+x ./_Scripts/install.sh
- chmod a+x ./_Scripts/build.sh

install:
- ./_Scripts/install.sh

script:
- ./_Scripts/build.sh
