language: objective-c
osx_image: xcode8.1
rvm:
- 2.2
before_install:
- chmod a+x ./Scripts/install.sh
- chmod a+x ./Scripts/build.sh
install:
- ./Scripts/install.sh
script:
- ./Scripts/build.sh

# only run builds on pushes to the master branch
branches:
  only:
  - master

# send email notifications when the build changes from succeeding to broken
notifications:
  email:
    on_success: never
    on_failure: change
